export type Locale = 'en' | 'ar';

export const LOCALES: Locale[] = ['en', 'ar'];

export const dictionary = {
  en: {
    // brand
    brandName: 'Cedar',
    tagline: 'Premium Marketplace, Delivered',

    // nav
    home: 'Home',
    categories: 'Categories',
    search: 'Search',
    about: 'About',
    contact: 'Contact',
    wishlist: 'Wishlist',
    cart: 'Cart',
    orders: 'Orders',
    profile: 'Profile',
    notifications: 'Notifications',
    login: 'Login',
    register: 'Register',
    logout: 'Logout',
    admin: 'Admin',

    // home sections
    todaysDeals: "Today's Deals",
    flashSale: 'Flash Sale',
    featuredProducts: 'Featured Products',
    trending: 'Trending Now',
    bestSellers: 'Best Sellers',
    newArrivals: 'New Arrivals',
    shopByCategory: 'Shop by Category',
    topBrands: 'Top Brands',
    newsletter: 'Newsletter',
    customerReviews: 'Customer Reviews',
    viewAll: 'View all',
    endsIn: 'Ends in',

    // hero
    heroTitle: 'Discover Premium Products, Delivered to Your Door',
    heroSubtitle: 'Shop thousands of curated products with Cash on Delivery across the region.',
    shopNow: 'Shop Now',
    exploreDeals: 'Explore Deals',

    // product
    addToCart: 'Add to Cart',
    buyNow: 'Buy Now',
    outOfStock: 'Out of Stock',
    inStock: 'In Stock',
    description: 'Description',
    specifications: 'Specifications',
    reviews: 'Reviews',
    questions: 'Questions',
    seller: 'Seller',
    shipping: 'Shipping',
    relatedProducts: 'Related Products',
    frequentlyBoughtTogether: 'Frequently Bought Together',
    sku: 'SKU',
    brand: 'Brand',
    category: 'Category',
    quantity: 'Quantity',
    writeReview: 'Write a Review',
    askQuestion: 'Ask a Question',
    rating: 'Rating',
    verifiedPurchase: 'Verified Purchase',

    // cart
    cartEmpty: 'Your cart is empty',
    cartEmptyDesc: 'Browse our catalog and add items to your cart.',
    continueShopping: 'Continue Shopping',
    subtotal: 'Subtotal',
    deliveryCost: 'Delivery Cost',
    discount: 'Discount',
    total: 'Total',
    proceedToCheckout: 'Proceed to Checkout',
    remove: 'Remove',
    couponCode: 'Coupon Code',
    apply: 'Apply',

    // checkout
    checkout: 'Checkout',
    cashOnDelivery: 'Cash on Delivery',
    customerName: 'Customer Name',
    phone: 'Phone',
    country: 'Country',
    city: 'City',
    area: 'Area',
    street: 'Street',
    building: 'Building',
    notes: 'Notes',
    estimatedDelivery: 'Estimated Delivery',
    placeOrder: 'Place Order',
    orderPlaced: 'Order placed successfully!',
    selectCountry: 'Select country',

    // auth
    email: 'Email',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    fullName: 'Full Name',
    forgotPassword: 'Forgot Password?',
    dontHaveAccount: "Don't have an account?",
    haveAccount: 'Already have an account?',
    createAccount: 'Create Account',
    signIn: 'Sign In',
    resetPassword: 'Reset Password',
    sendResetLink: 'Send Reset Link',
    backToLogin: 'Back to Login',

    // footer
    aboutUs: 'About Us',
    customerService: 'Customer Service',
    policies: 'Policies',
    faq: 'FAQ',
    privacy: 'Privacy Policy',
    terms: 'Terms of Service',
    deliveryPolicy: 'Delivery Policy',
    returnPolicy: 'Return Policy',
    followUs: 'Follow Us',
    allRightsReserved: 'All rights reserved',
    subscribeNewsletter: 'Subscribe to Newsletter',
    yourEmail: 'Your email',
    subscribe: 'Subscribe',

    // misc
    loading: 'Loading…',
    noResults: 'No results found',
    searchPlaceholder: 'Search products, brands and categories…',
    voiceSearch: 'Voice Search',
    filters: 'Filters',
    sortBy: 'Sort by',
    priceLowHigh: 'Price: Low to High',
    priceHighLow: 'Price: High to Low',
    newest: 'Newest',
    topRated: 'Top Rated',
    bestSelling: 'Best Selling',
    clearAll: 'Clear All',
    searchHistory: 'Search History',
    popularSearches: 'Popular Searches',
    suggestions: 'Suggestions',
    applyFilters: 'Apply Filters',
  },
  ar: {
    brandName: 'سيدار',
    tagline: 'سوق المتاجر المتميز، يصلك أينما كنت',

    home: 'الرئيسية',
    categories: 'الفئات',
    search: 'البحث',
    about: 'من نحن',
    contact: 'تواصل معنا',
    wishlist: 'المفضلة',
    cart: 'السلة',
    orders: 'الطلبات',
    profile: 'الملف الشخصي',
    notifications: 'الإشعارات',
    login: 'تسجيل الدخول',
    register: 'إنشاء حساب',
    logout: 'تسجيل الخروج',
    admin: 'لوحة التحكم',

    todaysDeals: 'عروض اليوم',
    flashSale: 'تخفيضات سريعة',
    featuredProducts: 'منتجات مميزة',
    trending: 'الأكثر رواجاً',
    bestSellers: 'الأكثر مبيعاً',
    newArrivals: 'وصل حديثاً',
    shopByCategory: 'تسوق حسب الفئة',
    topBrands: 'أبرز الماركات',
    newsletter: 'النشرة البريدية',
    customerReviews: 'آراء العملاء',
    viewAll: 'عرض الكل',
    endsIn: 'ينتهي خلال',

    heroTitle: 'اكتشف منتجات فاخرة تصلك إلى باب منزلك',
    heroSubtitle: 'تسوق آلاف المنتجات المختارة مع الدفع عند الاستلام عبر المنطقة.',
    shopNow: 'تسوق الآن',
    exploreDeals: 'استكشف العروض',

    addToCart: 'أضف إلى السلة',
    buyNow: 'اشترِ الآن',
    outOfStock: 'غير متوفر',
    inStock: 'متوفر',
    description: 'الوصف',
    specifications: 'المواصفات',
    reviews: 'التقييمات',
    questions: 'الأسئلة',
    seller: 'البائع',
    shipping: 'الشحن',
    relatedProducts: 'منتجات ذات صلة',
    frequentlyBoughtTogether: 'يشترى معاً بشكل متكرر',
    sku: 'رمز المنتج',
    brand: 'الماركة',
    category: 'الفئة',
    quantity: 'الكمية',
    writeReview: 'اكتب تقييماً',
    askQuestion: 'اطرح سؤالاً',
    rating: 'التقييم',
    verifiedPurchase: 'عملية شراء موثقة',

    cartEmpty: 'سلتك فارغة',
    cartEmptyDesc: 'تصفح كتالوجنا وأضف منتجات إلى سلتك.',
    continueShopping: 'مواصلة التسوق',
    subtotal: 'المجموع الفرعي',
    deliveryCost: 'تكلفة التوصيل',
    discount: 'الخصم',
    total: 'الإجمالي',
    proceedToCheckout: 'المتابعة إلى الدفع',
    remove: 'إزالة',
    couponCode: 'رمز القسيمة',
    apply: 'تطبيق',

    checkout: 'الدفع',
    cashOnDelivery: 'الدفع عند الاستلام',
    customerName: 'اسم العميل',
    phone: 'الهاتف',
    country: 'الدولة',
    city: 'المدينة',
    area: 'المنطقة',
    street: 'الشارع',
    building: 'المبنى',
    notes: 'ملاحظات',
    estimatedDelivery: 'التوصيل المتوقع',
    placeOrder: 'تأكيد الطلب',
    orderPlaced: 'تم إنشاء الطلب بنجاح!',
    selectCountry: 'اختر الدولة',

    email: 'البريد الإلكتروني',
    password: 'كلمة المرور',
    confirmPassword: 'تأكيد كلمة المرور',
    fullName: 'الاسم الكامل',
    forgotPassword: 'نسيت كلمة المرور؟',
    dontHaveAccount: 'ليس لديك حساب؟',
    haveAccount: 'لديك حساب بالفعل؟',
    createAccount: 'إنشاء حساب',
    signIn: 'تسجيل الدخول',
    resetPassword: 'إعادة تعيين كلمة المرور',
    sendResetLink: 'إرسال رابط الإعادة',
    backToLogin: 'العودة لتسجيل الدخول',

    aboutUs: 'من نحن',
    customerService: 'خدمة العملاء',
    policies: 'السياسات',
    faq: 'الأسئلة الشائعة',
    privacy: 'سياسة الخصوصية',
    terms: 'شروط الخدمة',
    deliveryPolicy: 'سياسة التوصيل',
    returnPolicy: 'سياسة الإرجاع',
    followUs: 'تابعنا',
    allRightsReserved: 'جميع الحقوق محفوظة',
    subscribeNewsletter: 'اشترك في النشرة',
    yourEmail: 'بريدك الإلكتروني',
    subscribe: 'اشتراك',

    loading: 'جارٍ التحميل…',
    noResults: 'لا توجد نتائج',
    searchPlaceholder: 'ابحث عن منتجات وماركات وفئات…',
    voiceSearch: 'البحث الصوتي',
    filters: 'الفلاتر',
    sortBy: 'ترتيب حسب',
    priceLowHigh: 'السعر: من الأقل للأعلى',
    priceHighLow: 'السعر: من الأعلى للأقل',
    newest: 'الأحدث',
    topRated: 'الأعلى تقييماً',
    bestSelling: 'الأكثر مبيعاً',
    clearAll: 'مسح الكل',
    searchHistory: 'سجل البحث',
    popularSearches: 'عمليات بحث شائعة',
    suggestions: 'اقتراحات',
    applyFilters: 'تطبيق الفلاتر',
  },
} as const;

export type DictKey = keyof typeof dictionary['en'];

export function t(locale: Locale, key: DictKey): string {
  return dictionary[locale][key] ?? dictionary.en[key] ?? key;
}
